version: '2'

services:  
  webui:
    image: webui    
    container_name: webui
    build:
      context: ./src/webui
      dockerfile: Dockerfile
      args:
        source: ./build
    ports:
      - "5000:80"