version: '2'

services:  
  ci-build:
    image: microsoft/aspnetcore-build
    container_name: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./docker-web.sln && dotnet publish ./docker-web.sln -c Release -o ./build"